h5netcdf/h5netcdf

h5netcdf/core.py, h5netcdf/legacyapi.py, h5netcdf/tests/test_h5netcdf.py
=> Ignore chunk/filter options upon creating scalar variables.

.travis.yml, h5netcdf/tests/test_h5netcdf.py
=> Ignore _NCProperties attribute for now

.travis.yml, README.rst, h5netcdf/compat.py, h5netcdf/legacyapi.py, h5netcdf/tests/test_h5netcdf.py, setup.py
=> Add support for dtype=str to legacy API

README.rst, h5netcdf/__init__.py, h5netcdf/attrs.py, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> Add _NCProperties attribute

README.rst, h5netcdf/core.py, setup.py
@krischer does this look good to you?
=> Readme updates for v0.5.0

h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> Return HDF5 dim. scale max size if REFERENCE_LIST atttribute missing

.travis.yml, README.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py, setup.py
Bump version to v0.6.0
Fixes #44
=> Remove invalid netCDF warning when using compression filters

.gitignore, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
Goes along will pull request in xarray - https://github.com/pydata/xarray/pull/2782
note that commenting the pre-existing file check was a quick change to see if this works. The path checking logic will need to be changed before merging.
=> enable loading h5py file like objects

.travis.yml, h5netcdf/tests/test_h5netcdf.py
These are failing on Travis-CI with "OSError: [Errno 404] Not Found", e.g., see https://travis-ci.org/shoyer/h5netcdf/jobs/539292517
=> Disable h5pyd tests

.travis.yml, setup.py
- as suggested in #64 remove Python3.5 from build matrix
- also add Python3.8 to build matrix
=> MNT: remove Python3.5 / add Python3.8 in travis.yml

h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> FIX: address H5pyDeprecationWarnings

h5netcdf/tests/test_h5netcdf.py
=> use explicit access modes with h5py.File

h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
See #84 for in-depth analysis.
=> FIX: specifically check for vlen strings for string decoding

CHANGELOG.rst, h5netcdf/core.py
=> update ``decode_vlen_strings`` FutureWarning

CHANGELOG.rst, h5netcdf/attrs.py, h5netcdf/tests/test_h5netcdf.py
=> return empty bytes (b'' ) for h5py.Empty strings

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
This moves the handling of `_nc4_non_coord_` variables into `BaseVariable`.
needed for #101
=> handle _nc4_non_coord_ 

CHANGELOG.rst, README.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> Switch warning into error when using invalid netCDF features

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
This PullRequest refactors the dimension scale handling from creating/attaching at file close to an on-the-fly creation/attaching process. This improves performance drastically (see #101 for example).
The example added builds on the nice example at the [unidata blog ](https://www.unidata.ucar.edu/blogs/developer/en/entry/netcdf4_shared_dimensions).
- builds on #104
- replaces #101 (at least partly)
- closes #88
I'll rebase when #104 is merged.
=> Refactor dimension scale handling

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
As suggested in #96, this adds issue and pullrequest templates (based on xarray's).
=> add issue and pullrequest templates based on xarray's

MANIFEST.in
- add missing CHANGELOG.rst to source distribution
=> MNT: include CHANGELOG.rst in source distribution

h5netcdf/core.py
Closes https://github.com/h5netcdf/h5netcdf/issues/132
=> Improve decode_vlen_strings warning message

CHANGELOG.rst, README.rst, h5netcdf/core.py, setup.py
Release 0.13.0 fixes bug #128 and improves performance #104, #112.
=> release v0.13.0

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> return group name instead of full path name for legacy API

CHANGELOG.rst, README.rst, h5netcdf/legacyapi.py, h5netcdf/tests/test_h5netcdf.py
=> Add `endian` keyword argument to legacy API

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> WIP: allow 1d boolean indexers in legacy API

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/legacyapi.py, h5netcdf/tests/test_h5netcdf.py, licenses/H5PY_LICENSE.txt
=> implement new h5netcdf default chunksize

README.rst
=> Add note to readme.rst regarding track order

CHANGELOG.rst, README.rst, h5netcdf/core.py, h5netcdf/dimensions.py, h5netcdf/legacyapi.py, h5netcdf/tests/test_h5netcdf.py
=> Implement Dimension class

h5netcdf/attrs.py
In https://github.com/pydata/xarray/issues/6281 xarray's `h5netcdf` backend fails with the latest changes to attributes decoding.
The error was introduced by using `np.atleast_1d` to conveniently iterate over attribute arrays with the result of traversal of `np.string_` types. This prevented correct roundtripping ("<U" type conversion path in `h5py`).
To resolve this the `h5py` attribute isn't wrapped via `np.atleast_1d`. Instead specific checks using `np.isscalar` are used to correctly decode strings and pack into lists.
=> FIX: attributes scalar/array handling

.github/workflows/main.yml, CHANGELOG.rst, h5netcdf/attrs.py, h5netcdf/core.py, h5netcdf/dimensions.py, h5netcdf/tests/conftest.py, h5netcdf/tests/test_h5netcdf.py
This is combination of @ajelenak's work in #162, another branch in his fork (https://github.com/ajelenak/h5netcdf/tree/h5pyd-integ) and some fixes to hopefully make this work in CI.
=> hsds/h5pyd pytest 

README.rst, doc/conf.py, doc/index.rst, doc/readme.rst
Reorders documentation content as suggested by @shoyer in https://github.com/h5netcdf/h5netcdf/issues/113#issuecomment-1079807718.
=> MNT: reorder doc content

.github/workflows/main.yml, CHANGELOG.rst, doc/index.rst
=> REL: 1.0.0

.github/workflows/main.yml, CHANGELOG.rst, h5netcdf/tests/test_h5netcdf.py
=> MNT: add netCDF4 nightly test

CHANGELOG.rst, doc/devguide.rst, doc/feature.rst, doc/index.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> h5py 3.7.0 adaptions

CHANGELOG.rst
=> REL: 1.0.2

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
rework adding _FillValues-attribute, add tests to write/read VLEN str……ing _FillValues, add CHANGELOG.rst entry
=> rework adding _FillValues-attribute

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/dimensions.py, h5netcdf/tests/test_h5netcdf.py
- fix error creating dimensions with phony name scheme
- update _unlabeled_dimension_mix
=> dimension fixes (phony scheme and mixed scales)

.github/workflows/main.yml, CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> FIX: regression in __getitem__

h5netcdf/tests/test_h5netcdf.py
=> Ensure we don't create test nc files in the user's git repo

.github/workflows/main.yml, h5netcdf/core.py
Also added build-matrix for h5py=["3.6", "3.7"].
=> FIX:  boolean indexers

CHANGELOG.rst
=> REL: 1.1.0

.github/workflows/main.yml, CHANGELOG.rst, README.rst, environment.yml, h5netcdf/core.py, h5netcdf/dimensions.py, h5netcdf/tests/pytest.ini, h5netcdf/tests/test_h5netcdf.py, setup.cfg, setup.py
=> MNT: Remove h5py2 compatibility code

.github/workflows/main.yml
=> add netCDF4 and dask to xarray CI test run

.github/workflows/main.yml, CHANGELOG.rst, doc/devguide.rst, doc/index.rst, environment.yml
=> h5netcdf release 1.2.0

h5netcdf/core.py
=> Lint with ruff Oct 10, 2023

CHANGELOG.rst
=> release 1.3.0

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> ADD: Refactor fillvalue and dtype handling for user types, enhance tests

.github/workflows/main.yml, .pre-commit-config.yaml, CHANGELOG.rst, h5netcdf/__init__.py, h5netcdf/attrs.py, h5netcdf/core.py, h5netcdf/dimensions.py, h5netcdf/legacyapi.py, h5netcdf/tests/test_h5netcdf.py, pyproject.toml
=> MNT: CI and Lint

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> Support wrapping an h5py File object

.github/workflows/main.yml, CHANGELOG.rst, README.rst, doc/conf.py, h5netcdf/core.py
This adds lint/ci changes from #227, to make review experience better.
=> MNT: Lint and ci

CHANGELOG.rst, doc/devguide.rst, doc/index.rst
=> REL: v1.4.0

.github/workflows/main.yml, CHANGELOG.rst, h5netcdf/tests/test_h5netcdf.py
=> Fix complex and hdf5=1.10 tests

.github/workflows/main.yml, CHANGELOG.rst
=> run CI with Python 3.13 where appropriate, remove numpy 1 where necessary

.github/workflows/main.yml, CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/conftest.py, h5netcdf/tests/test_h5netcdf.py
Updates to workflow for h5pyd test
=> Fix for h5pyd workflow run

.github/workflows/main.yml
This adapts to changes in xarray.
=> Add pytest-mypy-plugins for xarray nightly test

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> Let h5netcdf.File(driver="h5pyd") force the use of h5pyd

.github/workflows/main.yml, CHANGELOG.rst, h5netcdf/tests/conftest.py, h5netcdf/tests/test_h5netcdf.py
=> fix hsds/h5pyd test fixture spinup issues

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
=> Avoid opening file with h5pyd just to check if it exists

CHANGELOG.rst, h5netcdf/core.py, h5netcdf/dimensions.py, h5netcdf/tests/test_h5netcdf.py
=> fix invalid string format specifier, match raises/warns with messages in test suite

CHANGELOG.rst
=> REL: 1.6.3

.github/ISSUE_TEMPLATE/bug_report.md, h5netcdf/core.py, h5netcdf/tests/test_h5netcdf.py
`pre-commit run --all-files` also removed a blank like from bug_report.md.
=> cleanup: pyupgrade --py39-plus

CHANGELOG.rst
=> REL: 1.6.4

CHANGELOG.rst, h5netcdf/tests/test_h5netcdf.py
=> fix unintentional changes in test suite
