h5netcdf/h5netcdf

- .travis.yml
- README.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
- setup.py
A few fixes.
1) both groups and variables can be lazily evaluated and,
2) no h5py object is stored in subsequent classes. This feature was causing segmentation faults when reading arrays with str datatype.
The changes are fairly minor with only a few additions to the hidden API.
> Lazy evaluation and no segmentation fault when reading str arrays

- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
See: pydata/xarray#994.
I also made a small change in `core.Group._create_dimension` when checking for unlimited dimensions: presently this throws an exception when `size=0`, which seems incorrect.
> Fix missing attribute exception when writing to groups

- MANIFEST.in
The current tarball hosted on PyPI is missing the test suite associated with the package. I added it manually to the source of the [Debian package](https://packages.debian.org/source/sid/python-h5netcdf), but it would be better if they were systematically included in future releases on PyPI, hence this PR.
> Include tests to the release tarball

- .travis.yml
- README.rst
- h5netcdf/__init__.py
- h5netcdf/attrs.py
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
- setup.py
Fixes #28
xref pydata/xarray#1536
New behavior:
```
In [1]: import h5netcdf
In [2]: f = h5netcdf.File('warning.h5')
In [3]: f.attrs['foo'] = 1j
/Users/shoyer/conda/envs/h5netcdf-dev/bin/ipython:1: FutureWarning: complex dtypes
are supported by h5py, but not part of the NetCDF API. You are writing an HDF5
file that is not a valid NetCDF file! In the future, this will be an error, unless
you set invalid_netcdf=True.
#!/bin/bash /Users/shoyer/conda/envs/h5netcdf-dev/bin/python.app
In [4]: f = h5netcdf.File('error.h5', invalid_netcdf=False)
In [5]: f.attrs['foo'] = 1j
CompatibilityError: complex dtypes are not a supported NetCDF feature, and are not
allowed by h5netcdf unless invalid_netcdf=True.
```
CC @dopplershift -- I would appreciate any feedback you might have on the error/warning …
> Warnings when using invalid netCDF features

- MANIFEST.in
My mistake for not verifying my first patch before hand. The tarball for version 0.4.0 on PyPI still lacks the test suite. This commit fixes it.
> Fixup inclusion of the tests in the source tarball

- .travis.yml
It's generally more up-to-date than the default channel, e.g., for dependencies like netCDF4-python.
Note that tests are currently failing, due to https://github.com/shoyer/h5netcdf/issues/32.
> Test using the conda-forge channel

- README.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
This PR adds support for unlimited dimensions.
I'm not very familiar with netncdf but as far as I can tell the underlying HDF5 data sets are automatically resized if required so that is what I implemented here. I think I caught the most common indexing patterns.
It is tested in the sense that netcdf can open the resulting files just fine and everything appears to be correct. There is also full test coverage for all changes and this PR does not change the behavior of limited dimensions.
It would be great if this could be merged with a subsequent release fairly soon as we have a number of downstream project that depend on it and we really need unlimited dimensions. Let me know if I can help with things!
> Adding support for unlimited dimensions

- .travis.yml
- h5netcdf/attrs.py
- h5netcdf/core.py
- h5netcdf/dimensions.py
- h5netcdf/utils.py
- setup.py
```
/home/users/me/Dev/h5netcdf/h5netcdf/dimensions.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import MutableMapping
```
I didn't try to keep the compatibility with Python 2.7 since we are in July 2019 (see https://python3statement.org/).
> Compatibility Python 3.8

- .travis.yml
- h5netcdf/tests/test_h5netcdf.py
fixes #61
fixes new issue installing incompatible h5pyd version for Python3.5
> FIX: install correct h5pyd version, use request.config in tests

- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
As suggested in #49 adds another check to only add h5py.Dataset to variables.
fixes #49
fixes #63
> FIX: only add h5py.Dataset to variables

- README.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
This PR adds naming for unlabeled dimensions (without dimension scales) in a netcdf style manner (`phony_dim_0` etc) instead of raising an error. 
This works nice in most cases (hdf5 files with no dimension scales at all). In mixing cases the naming might need improvement. ~~I did not find a way of having an overall count of the invented `phony_dim_N`, so with the proposed changes it the counting is per dataset/subgroup~~.
Xref: https://github.com/shoyer/h5netcdf/issues/43
> ENH: invent `phony_dim` names for unlabeled dimensions

- .github/workflows/main.yml
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
fixes #81 
How does it work?
- Keeps full backwards compatibility for `h5py` == 2.*
for `h5py` >= 3:
- If `legacy` API -> keeps conformance to netCDF4 (decoding strings by default, raise `TypeError` if `decode_strings` is explicitly set
- If `new` API -> keeps backwards compatibility for the moment (decoding strings by default, emit `FutureWarning` if `decode_strings` is not explicitly set, decoding can be deactivated by setting `decode_strings=False` )
- In future versions conformance with `h5py` >= 3 will be ensured by not decoding strings by default. String decoding can be requested by setting keyword argument `decode_strings=True`.
> FIX: adapt to string reading in h5py >= 3.0

- h5netcdf/core.py
A simple fix to include `h5pyd.Dataset` objects in the list of variables when scanning file content.
> Include h5pyd.Dataset objects as netCDF variables

- CHANGELOG.rst
- h5netcdf/core.py
- setup.py
At least the support for `h5py.Empty` strings justify a new release. Looking forward to see if the automatic upload works smoothly.
I've added the necessary changes as laid out in the [release workflow description](https://github.com/h5netcdf/h5netcdf/wiki#release-workflow) (first bullet point). The release date in CHANGELOG.rst is set to today. But it would be only minor thing to fix this, if we merge on another day.
@shoyer Please update PR if necessary and merge at your discretion. After merge the github release needs to be created (second bullet point of above release workflow) to finalize the release.
> release 0.11.0

- CHANGELOG.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
I think the default file mode for h5netcdf should be 'r' instead of 'a'. This matches netCDF4 library (https://unidata.github.io/netcdf4-python/#Dataset.__init__) and the default mode for Python's open().
As a new user of h5netcdf, I was puzzled why the modification dates of my netCDF files were being updated when I was only opening the files for read operations as I assumed the default file mode would have been read-only. Opening a file in read-only mode is the least surprising way and, in this case, the least destructive way to open netCDF file.
> Use 'r' for default file mode.

- CHANGELOG.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
This fixes an issue where `_NCProperties` isn't written when overwriting existing files.
- added a test which checks if attribute gets written
closes #111
> write _NCProperties when overwriting file (mode="w")

- CHANGELOG.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
This fixes an issue where dimension scales weren't created/attached when appending with ``mode="r+"``.
- added tests to check for scales when appending with `mode="r+"`
> Create/Attach dimension scales on append (``mode="r+"``)

- .github/workflows/main.yml
This "fixes" the CI failure by pinning netCDF to a version that seems to be compatible with whatever version of h5py and libnetcdf that mamba picks. netCDF4==1.5.3 was released around the same time as h5py==2.10.0.
> Pinned netCDF4

- CHANGELOG.rst
- h5netcdf/core.py
- setup.py
Referring to [this comment](https://github.com/h5netcdf/h5netcdf/pull/118#issuecomment-997421682) from @TomAugspurger a new version needs to be released:
Quoting from the comment:
> but getting a release out with #117 would be very helpful for projects like pangeo-forge.
#117 fixed a circular reference issue with ``h5py`` objects.
With this release other changes like:
- moving to default opening with `mode="r"` 
- minor changes in dimension scale handling
- error when using invalid netCDF features
are introduced.
> release v0.12.0

- CHANGELOG.rst
- h5netcdf/core.py
This retrieves the `max_dim_id` count on start if the file is writable and assigns the dimids on the fly.
Update: This changes the current behaviour of iterating over the groups/datasets at file close to iteration at file start. `dim_order` is assigned on the fly instead at file close.This is needed to create/attach and detach/delete dimension scales on the fly (in follow-up PR). 
needed for #101
> assign dimensions on creation

- .github/workflows/main.yml
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
distutils.version is deprecated and has started to issue warnings in CI.
Replacing with packaging.version which is the recommended replacement.
- added Python 3.10 to build matrix for h5py3
> Replace distutils.version with packaging.version

- CHANGELOG.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
This PR sets the order_tracked property to true by default, but for files that already exists, attempts to leave the property in the way it found them
> Ensure order is tracked by default

- CHANGELOG.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
Closes https://github.com/h5netcdf/h5netcdf/issues/136
<details> <summary>An earlier debugging attempt that I resolved</summary>
For the life of me i can't get the test to fail in pytest.
```
!git describe --tags
import h5netcdf
def _track_order(self):
from h5py.h5p import CRT_ORDER_INDEXED, CRT_ORDER_TRACKED
gcpl = self._h5group.id.get_create_plist()
attr_creation_order = gcpl.get_attr_creation_order()
order_tracked = bool(attr_creation_order & CRT_ORDER_TRACKED)
order_indexed = bool(attr_creation_order & CRT_ORDER_INDEXED)
return order_tracked and order_indexed
with h5netcdf.File("test_temp.nc", "w", track_order=True) as h5file:
assert _track_order(h5file)
for i in range(10):
h5file.attrs[f"key{i}"] = i
```
</details>
> Set track_order=False as default to avoid bug in h5py

- CHANGELOG.rst
- README.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
Review after: https://github.com/h5netcdf/h5netcdf/pull/140
> 0.13 branch Revert track_order=True avoiding a bug in h5py

- .github/workflows/main.yml
- MANIFEST.in
- h5netcdf/__init__.py
- h5netcdf/core.py
- pyproject.toml
- setup.py
This simplifies the versioning process relying only on the creation of the github release/tag. It helps downstream too to get comparable version numbers when building from git/github.
> MNT: use setuptools_scm for versioning, use pyproject.toml

- CHANGELOG.rst
- h5netcdf/attrs.py
- h5netcdf/tests/test_h5netcdf.py
- items are extracted from 0-dim and single element 1-dim attributes
- multi-element 1-dim attributes are returned as list (like netcdf4-python)
- bytes/string attributes are returned as strings decoded from their respective encoding (ascii/utf-8)
> fix array attributes and attributes decoding

- CHANGELOG.rst
- h5netcdf/attrs.py
- h5netcdf/tests/test_h5netcdf.py
> directly return non-string Empty-type attributes as numpy array, add test

- .github/workflows/main.yml
Final changes for release 0.15.0. 
- Use [pypa/build](https://github.com/pypa/build) to create sdist and universal wheel
Note: The 0.15 version line will be the last before h5netcdf 1.0. Major problems should be ruled out within the next 14 days.
> REL: 0.15.0

- CHANGELOG.rst
- README.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
- remove `_NCProperties` from existing file if writing invalid netcdf features
- warn users if `.nc` file extension is used writing invalid netcdf features
> remove `_NCProperties` from existing file if writing invalid netcdf features

- .gitignore
Mostly i want to test the CIs to see if i broke something in https://github.com/h5netcdf/h5netcdf/pull/185
> Add h5netcdf/_version.py to gitignore

- CHANGELOG.rst
- README.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
Closes: https://github.com/h5netcdf/h5netcdf/issues/143
> Make track_order True as default if h5py is 3.7.0 or greater

- .github/workflows/main.yml
- CHANGELOG.rst
- h5netcdf/core.py
- h5netcdf/tests/conftest.py
- h5netcdf/tests/test_h5netcdf.py
- pyproject.toml
This replaces the deprecated https://github.com/mamba-org/provision-with-micromamba with it's successor https://github.com/mamba-org/setup-micromamba
> MNT: move to setup-micromamba in CI

- CHANGELOG.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
Currently, for remote URLs `hpy5d` is used. However, it is desirable to allow the usage of the `ros3` HDF5 driver to read from remote URLs.
The following code does not work at the moment.
```python
import h5netcdf
f = h5netcdf.File("https://api.cloud.ifca.es:8080/swift/v1/IPCC-IA-Monthly/test2.nc", driver="ros3")
print(list(f))
```
This simple pull request allows to use the `ros3` driver with `h5py` ignoring `h5pyd`.
> Allow to use ros3 driver for remote url

- .github/workflows/main.yml
- CHANGELOG.rst
- README.rst
- doc/api.rst
- doc/legacyapi.rst
- h5netcdf/core.py
- h5netcdf/legacyapi.py
- h5netcdf/tests/test_h5netcdf.py
see #228 for transient vs committed types
> add VLType and CompoundType, commit complex compound type to file

- CHANGELOG.rst
- h5netcdf/core.py
- h5netcdf/tests/test_h5netcdf.py
libnetcdf4 allows zlib to be passed in as a compression string.
In xarray one would typically allow 'zlib' to be specified in
encoding['compression'] = 'zlib'
but the problem is that h5netcdf won't support this syntax.
This builds that compatibility layer
not quite related but: https://github.com/h5netcdf/h5netcdf/issues/240
> Allow zlib to be an alias for gzip
